# chezmoi:template:left-delimiter="#{{" right-delimiter=}}
[".local/share/plantuml.jar"]
refreshPeriod = "672h"
type = "file"
url = "https://netix.dl.sourceforge.net/project/plantuml/plantuml.jar"

[".tmux/plugins/tpm"]
refreshPeriod = "672h"
type = "git-repo"
url = "https://github.com/tmux-plugins/tpm"

## TODO rethink how to bootstrap fisher; this conflicts after the first install
# [".config/fish/functions/fisher.fish"]
# refreshPeriod = "672h"
# type = "file"
# url = "https://git.io/fisher"

[".stack/hooks/ghc-install.sh"]
executable = true
refreshPeriod = "672h"
type = "file"
url = "https://raw.githubusercontent.com/haskell/ghcup-hs/master/scripts/hooks/stack/ghc-install.sh"
