[".local/share/fonts"]
include = ["*/*.ttf"]
## Fira Code is stable, last release is from 2021
# refreshPeriod = "672h"
stripComponents = 1
type = "archive"
url = "https://github.com/tonsky/FiraCode/releases/download/{{ .versions.firaCode }}/Fira_Code_v{{ .versions.firaCode }}.zip"
