#!/bin/sh

command -v pbcopy > /dev/null && pbcopy $@; exit 0 # MacOS
command -v xsel > /dev/null && xsel --input --clipboard $@; exit 0 # Unix/Linux
command -v xclip > /dev/null && xclip -in -selection clipboard $@; exit 0 # Unix/Linux
command -v wl-copy > /dev/null && wl-copy $@; exit 0 # Wayland
command -v powershell.exe > /dev/null && powershell.exe Set-Clipboard $@; exit 0 # WSL

echo "unable to find any clipboard tool"; exit 1
