#!/bin/sh

command -V java >/dev/null 2>&1 || {
  echo "java not found"
  exit 1
}

command -V plantuml.jar >/dev/null 2>&1 || {
  echo "plantuml.jar not found"
  exit 1
}

exec java -Djava.awt.headless=true -jar "$(which plantuml.jar)" "$@"

# vim: ft=sh
