command -q git; or exit

### Vanilla git commands
## Git high-level commands
# Git main porcelain commands
complete -xc git -n __fish_use_subcommand -a add -d "Add file contents to the index"
complete -xc git -n __fish_use_subcommand -a am -d "Apply a series of patches from a mailbox"
complete -xc git -n __fish_use_subcommand -a archive -d "Create an archive of files from a named tree"
complete -xc git -n __fish_use_subcommand -a bisect -d "Use binary search to find the commit that introduced a bug"
complete -xc git -n __fish_use_subcommand -a branch -d "List, create, or delete branches"
complete -xc git -n __fish_use_subcommand -a bundle -d "Move objects and refs by archive"
complete -xc git -n __fish_use_subcommand -a checkout -d "Switch branches or restore working tree files"
complete -xc git -n __fish_use_subcommand -a cherry-pick -d "Apply the changes introduced by some existing commits"
complete -xc git -n __fish_use_subcommand -a citool -d "Graphical alternative to git-commit"
complete -xc git -n __fish_use_subcommand -a clean -d "Remove untracked files from the working tree"
complete -xc git -n __fish_use_subcommand -a clone -d "Clone a repository into a new directory"
complete -xc git -n __fish_use_subcommand -a commit -d "Record changes to the repository"
complete -xc git -n __fish_use_subcommand -a describe -d "Give an object a human readable name based on an available ref"
complete -xc git -n __fish_use_subcommand -a diff -d "Show changes between commits, commit and working tree, etc"
complete -xc git -n __fish_use_subcommand -a fetch -d "Download objects and refs from another repository"
complete -xc git -n __fish_use_subcommand -a format-patch -d "Prepare patches for e-mail submission"
complete -xc git -n __fish_use_subcommand -a gc -d "Cleanup unnecessary files and optimize the local repository"
complete -xc git -n __fish_use_subcommand -a grep -d "Print lines matching a pattern"
complete -xc git -n __fish_use_subcommand -a gui -d "A portable graphical interface to Git"
complete -xc git -n __fish_use_subcommand -a init -d "Create an empty Git repository or reinitialize an existing one"
complete -xc git -n __fish_use_subcommand -a log -d "Show commit logs"
complete -xc git -n __fish_use_subcommand -a merge -d "Join two or more development histories together"
complete -xc git -n __fish_use_subcommand -a mv -d "Move or rename a file, a directory, or a symlink"
complete -xc git -n __fish_use_subcommand -a notes -d "Add or inspect object notes"
complete -xc git -n __fish_use_subcommand -a pull -d "Fetch from and integrate with another repository or a local branch"
complete -xc git -n __fish_use_subcommand -a push -d "Update remote refs along with associated objects"
complete -xc git -n __fish_use_subcommand -a rebase -d "Reapply commits on top of another base tip"
complete -xc git -n __fish_use_subcommand -a reset -d "Reset current HEAD to the specified state"
complete -xc git -n __fish_use_subcommand -a revert -d "Revert some existing commits"
complete -xc git -n __fish_use_subcommand -a rm -d "Remove files from the working tree and from the index"
complete -xc git -n __fish_use_subcommand -a shortlog -d "Summarize git log output"
complete -xc git -n __fish_use_subcommand -a show -d "Show various types of objects"
complete -xc git -n __fish_use_subcommand -a stash -d "Stash the changes in a dirty working directory away"
complete -xc git -n __fish_use_subcommand -a status -d "Show the working tree status"
complete -xc git -n __fish_use_subcommand -a submodule -d "Initialize, update or inspect submodules"
complete -xc git -n __fish_use_subcommand -a tag -d "Create, list, delete or verify a tag object signed with GPG"
complete -xc git -n __fish_use_subcommand -a worktree -d "Manage multiple working trees"
complete -xc git -n __fish_use_subcommand -a gitk -d "The Git repository browser"
# Git ancillary commands: manipulators
complete -xc git -n __fish_use_subcommand -a config -d "Get and set repository or global options"
complete -xc git -n __fish_use_subcommand -a fast-export -d "Git data exporter"
complete -xc git -n __fish_use_subcommand -a fast-import -d "Backend for fast Git data importers"
complete -xc git -n __fish_use_subcommand -a filter-branch -d "Rewrite branches"
complete -xc git -n __fish_use_subcommand -a mergetool -d "Run merge conflict resolution tools to resolve merge conflicts"
complete -xc git -n __fish_use_subcommand -a pack-refs -d "Pack heads and tags for efficient repository access"
complete -xc git -n __fish_use_subcommand -a prune -d "Prune all unreachable objects from the object database"
complete -xc git -n __fish_use_subcommand -a reflog -d "Manage reflog information"
complete -xc git -n __fish_use_subcommand -a remote -d "Manage set of tracked repositories"
complete -xc git -n __fish_use_subcommand -a repack -d "Pack unpacked objects in a repository"
complete -xc git -n __fish_use_subcommand -a replace -d "Create, list, delete refs to replace objects"
# Git ancillary commands: interrogators
complete -xc git -n __fish_use_subcommand -a annotate -d "Annotate file lines with commit information"
complete -xc git -n __fish_use_subcommand -a blame -d "Show what revision and author last modified each line of a file"
complete -xc git -n __fish_use_subcommand -a cherry -d "Find commits yet to be applied to upstream"
complete -xc git -n __fish_use_subcommand -a count-objects -d "Count unpacked number of objects and their disk consumption"
complete -xc git -n __fish_use_subcommand -a difftool -d "Show changes using common diff tools"
complete -xc git -n __fish_use_subcommand -a fsck -d "Verifies the connectivity and validity of the objects in the database"
complete -xc git -n __fish_use_subcommand -a get-tar-commit-id -d "Extract commit ID from an archive created using git-archive"
complete -xc git -n __fish_use_subcommand -a help -d "Display help information about Git"
complete -xc git -n __fish_use_subcommand -a instaweb -d "Instantly browse your working repository in gitweb"
complete -xc git -n __fish_use_subcommand -a merge-tree -d "Show three-way merge without touching index"
complete -xc git -n __fish_use_subcommand -a rerere -d "Reuse recorded resolution of conflicted merges"
complete -xc git -n __fish_use_subcommand -a rev-parse -d "Pick out and massage parameters"
complete -xc git -n __fish_use_subcommand -a show-branch -d "Show branches and their commits"
complete -xc git -n __fish_use_subcommand -a verify-commit -d "Check the GPG signature of commits"
complete -xc git -n __fish_use_subcommand -a verify-tag -d "Check the GPG signature of tags"
complete -xc git -n __fish_use_subcommand -a whatchanged -d "Show logs with difference each commit introduces"
complete -xc git -n __fish_use_subcommand -a gitweb -d "Git web interface (web frontend to Git repositories)"
# Git foreign SCM interactions
complete -xc git -n __fish_use_subcommand -a archimport -d "Import an Arch repository into Git"
complete -xc git -n __fish_use_subcommand -a cvsexportcommit -d "Export a single commit to a CVS checkout"
complete -xc git -n __fish_use_subcommand -a cvsimport -d "Salvage your data out of another SCM people love to hate"
complete -xc git -n __fish_use_subcommand -a cvsserver -d "A CVS server emulator for Git"
complete -xc git -n __fish_use_subcommand -a imap-send -d "Send a collection of patches from stdin to an IMAP folder"
complete -xc git -n __fish_use_subcommand -a p4 -d "Import from and submit to Perforce repositories"
complete -xc git -n __fish_use_subcommand -a quiltimport -d "Applies a quilt patchset onto the current branch"
complete -xc git -n __fish_use_subcommand -a request-pull -d "Generates a summary of pending changes"
complete -xc git -n __fish_use_subcommand -a send-email -d "Send a collection of patches as emails"
complete -xc git -n __fish_use_subcommand -a svn -d "Bidirectional operation between a Subversion repository and Git"
## Git low-level commands
# manipulation commands
complete -xc git -n __fish_use_subcommand -a apply -d "Apply a patch to files and/or to the index"
complete -xc git -n __fish_use_subcommand -a checkout-index -d "Copy files from the index to the working tree"
complete -xc git -n __fish_use_subcommand -a commit-tree -d "Create a new commit object"
complete -xc git -n __fish_use_subcommand -a hash-object -d "Compute object ID and optionally creates a blob from a file"
complete -xc git -n __fish_use_subcommand -a index-pack -d "Build pack index file for an existing packed archive"
complete -xc git -n __fish_use_subcommand -a merge-file -d "Run a three-way file merge"
complete -xc git -n __fish_use_subcommand -a merge-index -d "Run a merge for files needing merging"
complete -xc git -n __fish_use_subcommand -a mktag -d "Creates a tag object"
complete -xc git -n __fish_use_subcommand -a mktree -d "Build a tree-object from ls-tree formatted text"
complete -xc git -n __fish_use_subcommand -a pack-objects -d "Create a packed archive of objects"
complete -xc git -n __fish_use_subcommand -a prune-packed -d "Remove extra objects that are already in pack files"
complete -xc git -n __fish_use_subcommand -a read-tree -d "Reads tree information into the index"
complete -xc git -n __fish_use_subcommand -a symbolic-ref -d "Read, modify and delete symbolic refs"
complete -xc git -n __fish_use_subcommand -a unpack-objects -d "Unpack objects from a packed archive"
complete -xc git -n __fish_use_subcommand -a update-index -d "Register file contents in the working tree to the index"
complete -xc git -n __fish_use_subcommand -a update-ref -d "Update the object name stored in a ref safely"
complete -xc git -n __fish_use_subcommand -a write-tree -d "Create a tree object from the current index"
# interrogation commands
complete -xc git -n __fish_use_subcommand -a cat-file -d "Provide content or type and size information for repository objects"
complete -xc git -n __fish_use_subcommand -a diff-files -d "Compares files in the working tree and the index"
complete -xc git -n __fish_use_subcommand -a diff-index -d "Compare a tree to the working tree or index"
complete -xc git -n __fish_use_subcommand -a diff-tree -d "Compares the content and mode of blobs found via two tree objects"
complete -xc git -n __fish_use_subcommand -a for-each-ref -d "Output information on each ref"
complete -xc git -n __fish_use_subcommand -a ls-files -d "Show information about files in the index and the working tree"
complete -xc git -n __fish_use_subcommand -a ls-remote -d "List references in a remote repository"
complete -xc git -n __fish_use_subcommand -a ls-tree -d "List the contents of a tree object"
complete -xc git -n __fish_use_subcommand -a merge-base -d "Find as good common ancestors as possible for a merge"
complete -xc git -n __fish_use_subcommand -a name-rev -d "Find symbolic names for given revs"
complete -xc git -n __fish_use_subcommand -a pack-redundant -d "Find redundant pack files"
complete -xc git -n __fish_use_subcommand -a rev-list -d "Lists commit objects in reverse chronological order"
complete -xc git -n __fish_use_subcommand -a show-index -d "Show packed archive index"
complete -xc git -n __fish_use_subcommand -a show-ref -d "List references in a local repository"
complete -xc git -n __fish_use_subcommand -a unpack-file -d "Creates a temporary file with a blob’s contents"
complete -xc git -n __fish_use_subcommand -a var -d "Show a Git logical variable"
complete -xc git -n __fish_use_subcommand -a verify-pack -d "Validate packed Git archive files"
# Synching repositories
complete -xc git -n __fish_use_subcommand -a daemon -d "A really simple server for Git repositories"
complete -xc git -n __fish_use_subcommand -a fetch-pack -d "Receive missing objects from another repository"
complete -xc git -n __fish_use_subcommand -a http-backend -d "Server side implementation of Git over HTTP"
complete -xc git -n __fish_use_subcommand -a send-pack -d "Push objects over Git protocol to another repository"
complete -xc git -n __fish_use_subcommand -a update-server-info -d "Update auxiliary info file to help dumb servers"
complete -xc git -n __fish_use_subcommand -a http-fetch -d "Download from a remote Git repository via HTTP"
complete -xc git -n __fish_use_subcommand -a http-push -d "Push objects over HTTP/DAV to another repository"
complete -xc git -n __fish_use_subcommand -a parse-remote -d "Routines to help parsing remote repository access parameters"
complete -xc git -n __fish_use_subcommand -a receive-pack -d "Receive what is pushed into the repository"
complete -xc git -n __fish_use_subcommand -a shell -d "Restricted login shell for Git-only SSH access"
complete -xc git -n __fish_use_subcommand -a upload-archive -d "Send archive back to git-archive"
complete -xc git -n __fish_use_subcommand -a upload-pack -d "Send objects packed back to git-fetch-pack"
# Internal helper commands
complete -xc git -n __fish_use_subcommand -a check-attr -d "Display gitattributes information"
complete -xc git -n __fish_use_subcommand -a check-ignore -d "Debug gitignore / exclude files"
complete -xc git -n __fish_use_subcommand -a check-mailmap -d "Show canonical names and email addresses of contacts"
complete -xc git -n __fish_use_subcommand -a check-ref-format -d "Ensures that a reference name is well formed"
complete -xc git -n __fish_use_subcommand -a column -d "Display data in columns"
complete -xc git -n __fish_use_subcommand -a credential -d "Retrieve and store user credentials"
complete -xc git -n __fish_use_subcommand -a credential-cache -d "Helper to temporarily store passwords in memory"
complete -xc git -n __fish_use_subcommand -a credential-store -d "Helper to store credentials on disk"
complete -xc git -n __fish_use_subcommand -a fmt-merge-msg -d "Produce a merge commit message"
complete -xc git -n __fish_use_subcommand -a interpret-trailers -d "add or parse structured information in commit messages"
complete -xc git -n __fish_use_subcommand -a mailinfo -d "Extracts patch and authorship from a single e-mail message"
complete -xc git -n __fish_use_subcommand -a mailsplit -d "Simple UNIX mbox splitter program"
complete -xc git -n __fish_use_subcommand -a merge-one-file -d "The standard helper program to use with git-merge-index"
complete -xc git -n __fish_use_subcommand -a patch-id -d "Compute unique ID for a patch"
complete -xc git -n __fish_use_subcommand -a sh-i18n -d "Git’s i18n setup code for shell scripts"
complete -xc git -n __fish_use_subcommand -a sh-setup -d "Common Git shell script setup code"
complete -xc git -n __fish_use_subcommand -a stripspace -d "Remove unnecessary whitespace"

### Custom git aliases
# true aliases (shorter versions of vanilla commands)
complete -xc git -n __fish_use_subcommand -a s -d "status: Show the working tree status"
complete -xc git -n __fish_use_subcommand -a co -d "checkout: Switch branches or restore working tree files"
complete -xc git -n __fish_use_subcommand -a cherrypick -d "cherry-pick: Apply the changes introduced by some existing commits"
complete -xc git -n __fish_use_subcommand -a cherry -d "cherry-pick: Apply the changes introduced by some existing commits"
complete -xc git -n __fish_use_subcommand -a cp -d "cherry-pick: Apply the changes introduced by some existing commits"
# complex aliases
complete -xc git -n __fish_use_subcommand -a unstage -d "unstage changes (reset -q HEAD --)"
complete -xc git -n __fish_use_subcommand -a discard -d "discard changes (checkout --)"
complete -xc git -n __fish_use_subcommand -a uncommit -d "uncommit changes (reset --mixed HEAD~)"
complete -xc git -n __fish_use_subcommand -a amend -d "amend commit (commit --amend --all)"
complete -xc git -n __fish_use_subcommand -a hreset -d "hard reset (reset --hard)"
complete -xc git -n __fish_use_subcommand -a fpush -d "force push ❤️ (push --force)"
complete -xc git -n __fish_use_subcommand -a c -d "commit adding files and message (commit -am)"
complete -xc git -n __fish_use_subcommand -a sclone -d "TODO (clone --depth=1)"
complete -xc git -n __fish_use_subcommand -a df -d "TODO (diff --color --color-words --abbrev)"
complete -xc git -n __fish_use_subcommand -a lg -d "TODO (log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --)"
complete -xc git -n __fish_use_subcommand -a diff -d "TODO (diff --word-diff)"
complete -xc git -n __fish_use_subcommand -a reup -d "TODO (rebase-update)"
complete -xc git -n __fish_use_subcommand -a d -d "Show the diff between the latest commit and the current state (diff-index --quiet HEAD -- || clear; diff --no-pager --patch-with-stat)"
complete -xc git -n __fish_use_subcommand -a fixup -d "Fixup staged changes to specified commit"
complete -xc git -n __fish_use_subcommand -a fixit -d "Commit staged changes into specific commit w/o opening editor"
complete -xc git -n __fish_use_subcommand -a scraplastcommit -d "remove changes (reset --hard HEAD^)"
complete -xc git -n __fish_use_subcommand -a unwindlastcommit -d "keep your changes (reset --soft HEAD^)"
complete -xc git -n __fish_use_subcommand -a reverselastcommit -d "generate a changeset to reverse a previous commit (revert HEAD)"
complete -xc git -n __fish_use_subcommand -a nevermind -d "reset --hard HEAD && clean -d -f"
complete -xc git -n __fish_use_subcommand -a graph -d "TODO (log --graph -10 --branches --remotes --tags  --format=format:'%Cgreen%h %Creset• %<(75,trunc)%s (%cN, %cr) %Cred%d' --date-order)"
complete -xc git -n __fish_use_subcommand -a precommit -d "TODO (diff --cached --diff-algorithm=minimal -w)"
complete -xc git -n __fish_use_subcommand -a ls -d "list commits in short form, with colors and branch/tag annotations"
complete -xc git -n __fish_use_subcommand -a ll -d "List commits showing changed files"
complete -xc git -n __fish_use_subcommand -a lnc -d "List commits with no colors for unix piping"
complete -xc git -n __fish_use_subcommand -a lds -d "List oneline commits showing dates"
complete -xc git -n __fish_use_subcommand -a le -d "short log (log --oneline --decorate)"
complete -xc git -n __fish_use_subcommand -a filelog -d "see all the commits related to a file, with the diff of the changes"
complete -xc git -n __fish_use_subcommand -a fl -d "see all the commits related to a file, with the diff of the changes"
complete -xc git -n __fish_use_subcommand -a dl -d "check what was in the last commit"
complete -xc git -n __fish_use_subcommand -a dlc -d "Show a diff last commit"
complete -xc git -n __fish_use_subcommand -a diffunc -d "Diff uncommitted changes"
complete -xc git -n __fish_use_subcommand -a dr -d "Show content (full diff) of a commit given a revision"
complete -xc git -n __fish_use_subcommand -a lc -d "Show content (full diff) of a commit given a revision"
complete -xc git -n __fish_use_subcommand -a diffr -d "Show content (full diff) of a commit given a revision"
complete -xc git -n __fish_use_subcommand -a f -d "Find a file path in codebase"
complete -xc git -n __fish_use_subcommand -a grep -d "Search/grep your entire codebase for a string"
complete -xc git -n __fish_use_subcommand -a gr -d "Search/grep your entire codebase for a string"
complete -xc git -n __fish_use_subcommand -a gra -d "Grep from root folder"
complete -xc git -n __fish_use_subcommand -a la -d "List all git aliases an their comments"
complete -xc git -n __fish_use_subcommand -a lasttag -d "show last tag"
complete -xc git -n __fish_use_subcommand -a lt -d "show last tag"
complete -xc git -n __fish_use_subcommand -a short-recent -d "show recent branches"
complete -xc git -n __fish_use_subcommand -a fza -d "fuzzy add using fzf"
complete -xc git -n __fish_use_subcommand -a fco -d "fuzzy switch branch"
complete -xc git -n __fish_use_subcommand -a ffix -d "fuzzy fix staged changes into existing commit"
complete -xc git -n __fish_use_subcommand -a frebase -d "fuzzy rebase interactive choose existing commit to start from"
complete -xc git -n __fish_use_subcommand -a fed -d "fuzzy edit untracked/modified files"
complete -xc git -n __fish_use_subcommand -a fedconflicts -d "fuzzy edit files in conflict state"
complete -xc git -n __fish_use_subcommand -a fgrep -d "fuzzy gitgrep working tree for pattern and choose file(s) to edit"
complete -xc git -n __fish_use_subcommand -a fedlog -d "fuzzy select past commit, and edit current state of file(s) changed in it"
complete -xc git -n __fish_use_subcommand -a freset -d "fuzzy reset back to prior commit"
complete -xc git -n __fish_use_subcommand -a yolo -d "amend and force push without interaction :D"
