# @fish-lsp-disable-next-line 2001
complete -c remake -a '(remake --tasks | awk \'{printf $1"\t"; $1=""}1\')'

complete -c remake -l no-extended-errors -d 'Do not give additional error reporting.'
complete -c remake -l no-print-directory -d 'Turn off -w, even if it was turned on implicitly.'
complete -c remake -l no-readline -d 'Do not use GNU ReadLine in debugger.'
complete -c remake -l no-silent -d 'Echo recipes (disable --silent mode).'
complete -c remake -l targets -d 'Give list of explicitly-named targets.'
complete -c remake -l tasks -d 'Give list of targets which have descriptions associated with them.'
complete -c remake -l trace -d 'Print tracing information.'
complete -c remake -l warn-undefined-variables -d 'Warn when an undefined variable is referenced.'
complete -c remake -s ! -l post-mortem -d 'Go into debugger on error. Same as --debugger --debugger-stop=error'
complete -c remake -s B -l always-make -d 'Unconditionally make all targets.'
complete -c remake -s C -l directory -d 'Change to DIRECTORY before doing anything.'
complete -c remake -s L -l check-symlink-times -d 'Use the latest mtime between symlinks and target.'
complete -c remake -s R -l no-builtin-variables -d 'Disable the built-in variable settings.'
complete -c remake -s S -l no-keep-going -l stop -d 'Turns off -k.'
complete -c remake -s X -l debugger -d 'Enter debugger.'
complete -c remake -s c -l search-parent -d 'Search parent directories for Makefile.'
complete -c remake -s d -d 'Print lots of debugging information.'
complete -c remake -s e -l environment-overrides -d 'Environment variables override makefiles.'
complete -c remake -s h -l help -d 'Print this message and exit.'
complete -c remake -s i -l ignore-errors -d 'Ignore errors from recipes.'
complete -c remake -s k -l keep-going -d 'Keep going when some targets can\'t be made.'
complete -c remake -s n -l just-print -l dry-run -l recon -d 'Don\'t actually run any recipe just print them.'
complete -c remake -s p -l print-data-base -d 'Print make\'s internal database.'
complete -c remake -s q -l question -d 'Run no recipe exit status says if up to date.'
complete -c remake -s r -l no-builtin-rules -d 'Disable the built-in implicit rules.'
complete -c remake -s s -l silent -l quiet -d 'Don\'t echo recipes.'
complete -c remake -s t -l touch -d 'Touch targets instead of remaking them.'
complete -c remake -s v -l version -d 'Print the version number of make and exit.'
complete -c remake -s v -l version -d 'Print the version number of make and exit.'
complete -c remake -s w -l print-directory -d 'Print the current directory.'
complete -fc remake -s O -l output-sync -d 'Synchronize output of parallel jobs by TYPE.'
complete -fc remake -s P -l profile -d 'Print profiling information for each target using FORMAT. Defaults to "callgrind"'
complete -fc remake -s j -l jobs -d 'Allow N jobs at once infinite jobs with no arg.'
complete -fc remake -s l -l load-average -l max-load -d 'Don\'t start multiple jobs unless load is below N.'
complete -rFc remake -s W -l what-if -l new-file -l assume-new -d 'Consider FILE to be infinitely new.'
complete -rFc remake -s f -l file -l makefile -d 'Read the file as a makefile.'
complete -rFc remake -s o -l old-file -l assume-old -d 'Consider FILE to be very old and don\'t remake it.'
complete -xc remake -l debug -d 'Print various types of debugging information.'
complete -xc remake -l debugger-stop -a '(string collect goal preread preaction full error fatal)' -d 'Which point to enter debugger. Only makes sense with -X set.'
complete -xc remake -l profile-directory -a '(__fish_complete_directories)' -d 'Output profiling data to the DIR directory.'
complete -xc remake -l verbosity -a '(string collect terse no-header full)' -d 'Set verbosity level. The default is "full".'
complete -xc remake -s E -l eval -d 'Evaluate a string as a makefile statement.'
complete -xc remake -s I -l include-dir -a '(__fish_complete_directories)' -d 'Search the directory for included makefiles.'
complete -xc remake -s x -l trace -a '(string collect command read normal noshell full)' -d 'Trace command execution TYPE. Default is "normal"'
