#!/usr/bin/env bash
# vim: ft=bash
# === EDIT FILE LOCATIONS BELOW ===

# Your todo.txt directory (this should be an absolute path)
#export TODO_DIR="/Users/gina/Documents/todo"
export TODO_DIR=$HOME/Dropbox

# Your todo/done/report.txt locations
export TODO_FILE="$TODO_DIR/todo.txt"
export DONE_FILE="$TODO_DIR/done.txt"
export REPORT_FILE="$TODO_DIR/report.txt"

# You can customize your actions directory location
#export TODO_ACTIONS_DIR="$HOME/.todo.actions.d"

# == EDIT FILE LOCATIONS ABOVE ===

# === COLOR MAP ===

## Text coloring and formatting is done by inserting ANSI escape codes.
## If you have re-mapped your color codes, or use the todo.txt
## output in another output system (like Conky), you may need to
## over-ride by uncommenting and editing these defaults.
## If you change any of these here, you also need to uncomment
## the defaults in the COLORS section below. Otherwise, todo.txt
## will still use the defaults!

export BLACK='\\033[0;30m'
export RED='\\033[0;31m'
export GREEN='\\033[0;32m'
export BROWN='\\033[0;33m'
export BLUE='\\033[0;34m'
export PURPLE='\\033[0;35m'
export CYAN='\\033[0;36m'
export YELLOW='\\033[0;33m'
export ORANGE='\\033[38;5;208m'
export LIGHT_GREY='\\033[1;37m'
export DARK_GREY='\\033[1;30m'
export LIGHT_RED='\\033[1;31m'
export LIGHT_GREEN='\\033[1;32m'
export LIGHT_BLUE='\\033[1;34m'
export LIGHT_PURPLE='\\033[1;35m'
export LIGHT_CYAN='\\033[1;36m'
export LIGHT_YELLOW='\\033[1;93m'
export WHITE='\\033[1;37m'
export DEFAULT='\\033[0m'

# === COLORS ===

## Uncomment and edit to override these defaults.
## Reference the constants from the color map above,
## or use $NONE to disable highlighting.
#
# Priorities can be any upper-case letter.
# A,B,C are highlighted; you can add coloring for more.
#

export PRI_A='\\033[38;2;253;82;48m'
export PRI_B='\\033[38;2;250;94;38m'
export PRI_C='\\033[38;2;247;106;30m'
export PRI_D='\\033[38;2;242;119;22m'
export PRI_E='\\033[38;2;236;131;16m'
export PRI_F='\\033[38;2;228;144;10m'
export PRI_G='\\033[38;2;220;157;6m'
export PRI_H='\\033[38;2;211;169;3m'
export PRI_I='\\033[38;2;201;180;1m'
export PRI_J='\\033[38;2;190;192;1m'
export PRI_K='\\033[38;2;179;202;1m'
export PRI_L='\\033[38;2;167;212;3m'
export PRI_M='\\033[38;2;155;221;6m'
export PRI_N='\\033[38;2;142;229;11m'
export PRI_O='\\033[38;2;130;236;16m'
export PRI_P='\\033[38;2;117;242;23m'
export PRI_Q='\\033[38;2;104;247;31m'
export PRI_R='\\033[38;2;92;251;40m'
export PRI_S='\\033[38;2;80;253;49m'
export PRI_T='\\033[38;2;68;254;60m'
export PRI_U='\\033[38;2;58;254;71m'
export PRI_V='\\033[38;2;47;253;82m'
export PRI_W='\\033[38;2;38;250;94m'
export PRI_X='\\033[38;2;29;246;107m'
export PRI_Y='\\033[38;2;22;241;119m'
export PRI_Z='\\033[38;2;15;235;132m'

# There is highlighting for tasks that have been done,
# but haven't been archived yet.
#
export COLOR_DONE='\\033[9;90m'

# There is highlighting for projects, contexts, dates, and item numbers.
#
export COLOR_PROJECT=$LIGHT_BLUE
export COLOR_CONTEXT=$GREEN
export COLOR_DATE='\\033[38;5;102m'
export COLOR_NUMBER='\\033[38;5;201m'

# There is highlighting for metadata key:value pairs e.g.
# DUE:2006-08-01 or note:MYNOTE
#
export COLOR_META=$YELLOW

# === BEHAVIOR ===

## customize list output
#
# TODOTXT_SORT_COMMAND will filter after line numbers are
# inserted, but before colorization, and before hiding of
# priority, context, and project.
#
# export TODOTXT_SORT_COMMAND='env LC_COLLATE=C sort -f -k2'

# TODOTXT_FINAL_FILTER will filter list output after colorization,
# priority hiding, context hiding, and project hiding. That is,
# just before the list output is displayed.
#
# export TODOTXT_FINAL_FILTER='cat'

# Auto-archive tasks automatically on completion
# TODOTXT_AUTO_ARCHIVE=1

# Prepend the current date to a task automatically
export TODOTXT_DATE_ON_ADD=1

# Forces actions without confirmation or interactive input
# TODOTXT_FORCE=0

# Preserve line numbers or automatically remove blank lines on deletion
export TODOTXT_PRESERVE_LINE_NUMBERS=0

# Plain mode turns off colors
export TODOTXT_PLAIN=0

# default priority of added tasks [A-Z]
# TODOTXT_PRIORITY_ON_ADD=Z
# Disables TODOTXT_FINAL_FILTER
# TODOTXT_DISABLE_FILTER=1
# TODOTXT_DEFAULT_ACTION='ls'
# TODOTXT_SIGIL_BEFORE_PATTERN=
# TODOTXT_SIGIL_VALID_PATTERN=.*
# TODOTXT_SIGIL_AFTER_PATTERN=
