#!/bin/bash
# vim: ft=bash

FILTERS="@dev +kubegraph"

SCRIPT_NAME=$(basename "$0")

[[ "$1" = "usage" ]] && {
  echo "    ${TODO_SH} [-fhpantvV] [-d todo_config] ${SCRIPT_NAME} <action> [task_number] [task_description]"
  echo "      Do actions on ${FILTERS} tasks"
  exit 0
}

# remove script name
shift

# extract the command
COMMAND="$1"
shift

"${TODO_FULL_SH}" "${COMMAND}" "$* ${FILTERS}"
