---@class CGWindow
---@field kCGWindowLayer integer
---@field kCGWindowMemoryUsage integer
---@field kCGWindowIsOnscreen boolean
---@field kCGWindowSharingState integer
---@field kCGWindowOwnerPID integer
---@field kCGWindowOwnerName string
---@field kCGWindowNumber integer
---@field kCGWindowStoreType integer
---@field kCGWindowAlpha integer
---@field kCGWindowBounds CGWindowBounds
