---@class ProcessInfo
---@field build string
---@field bundlePath string
---@field debugBuild boolean
---@field buildTime string
---@field processID number
---@field version string
---@field resourcePath string
---@field executablePath string
---@field bundleID string
