## See https://pre-commit.com for more information
## See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
    args:
    - --assume-in-merge
  - id: check-vcs-permalinks
  - id: check-yaml
  - id: check-xml
    types: [file, non-executable, text]
    types_or: [xml, plist]
  - id: detect-private-key
  # - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: mixed-line-ending
  # - id: no-commit-to-branch
  - id: trailing-whitespace
- repo: https://github.com/editorconfig-checker/editorconfig-checker.python
  rev: 2.7.3
  hooks:
  - id: editorconfig-checker
    exclude: vscode/.config/Code/User/globalStorage/.*
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.41.0
  hooks:
  - id: markdownlint
- repo: https://github.com/detailyang/pre-commit-shell
  rev: 1.0.5
  hooks:
  - id: shell-lint
    name: lint sh
    args: [-x, -s, sh]
    exclude: bash/.*
  - id: shell-lint
    name: lint bash
    args: [-x, -s, bash]
    files: bash/.*
ci:
  autofix_commit_msg: "ci: pre-commit autofix"
  autoupdate_commit_msg: "ci: pre-commit autoupdate"
  autofix_prs: true
  skip:
  - shell-lint
