[default]
extend-ignore-identifiers-re = ["LESS_TERMCAP_[a-z]{2}"]
extend-ignore-words-re = []
extend-ignore-re = []

[default.extend-identifiers]
automaticEmojiSubstitutionEnablediMessage = "automaticEmojiSubstitutionEnablediMessage"
## GPG's fingerprint colon format
fpr = "fpr"
hda = "hda" # hard-drive A

[default.extend-words]

[files]
extend-exclude = [
  # keep-sorted start
  "*.asc",
  "CHANGELOG.md",
  "modules/programs/finicky/finicky.js",
  "secrets.yaml",
  # keep-sorted end
]
