# yaml-language-server: $schema=https://www.schemastore.org/yamllint.json
extends: default
rules:
  line-length: disable
  indentation: disable
  document-start:
    present: false
    level: warning
