# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: 3

vars:
  EJSON_KEY_ID: 6bf53a356a4b8abbc9a41ae2912787e56853e211653bb23d5da4a87ba6c9df6f

tasks:
  default:
    cmds:
    - task: secrets
    - task: checksum
  validate-secrets:
    desc: Checks and reports invalid secret references in the ejson template.
    cmd: >-
      gron .ejson/secrets.tmpl.json
      | grep "op://"
      | sed 's/[";]//g'
      | xargs -P 0 -I% bash -c 'echo "%" | op inject > /dev/null || echo %'
  checksum:
    desc: Update the saved checksum in the password vault.
    method: timestamp
    cmd: >-
      op item edit
      "ejson payload"
      "task checksum=$(cat .task/checksum/secrets)" || true
    sources:
    - .task/checksum/secrets
  secrets:
    vars:
      SOURCE: .ejson/secrets.tmpl.json
      TARGET: .ejson/secrets.json
    cmds:
    - op inject -f -i {{ .SOURCE | q }} -o {{ .TARGET | q }} || true
    - ejson encrypt .ejson/secrets.json
    - op document edit "ejson payload" .ejson/secrets.json || true
    deps:
    - key:Personal/ejson/password:{{ .EJSON_KEY_ID }}
    sources:
    - '{{ .SOURCE }}'
    generates:
    - '{{ .TARGET }}'
  key:
    desc: Extracts a local of the ejson key.
    deps:
    - key:Personal/ejson/password:{{ .EJSON_KEY_ID }}
  key:*:*:
    label: key:{{ index .MATCH 0 }}:{{ index .MATCH 1 }}
    vars:
      REF: 'op://{{ index .MATCH 0 }}'
      TARGET: '{{ joinPath .EJSON_KEYDIR (index .MATCH 1) }}'
    cmds:
    - mkdir -p {{ .EJSON_KEYDIR | q }}
    - >-
      op read --force --no-newline
      --file-mode 0600
      --out-file {{ .TARGET | q }}
      {{ .REF | q }}
    status:
    - test -f {{ .TARGET | q }}
  macos:fix:
    desc: Applies cleanup commands to solve system preference problems in MacOS.
    summary: >-
      Removes system preferences files to try and solve a mysterious issue where
      the System Settings app stops loading. The logs are as good as none.
    cmds:
    - rm ~/Library/Preferences/com.apple.systempreferences.plist || true
    - rm ~/Library/Application\ Scripts/com.apple.systempreferences.* || true
    - rm ~/Library/Group\ Containers/com.apple.systempreferences.* || true
    - rm ~/Library/Caches/com.apple.systempreferences || true
    - sudo rm -rfv /Library/Caches/com.apple.iconservices.store
