---@class FsAttributes
--- device the file resides on
---@field dev number
--- inode of the file
---@field ino number
--- type of the file (possible values are: file, directory, link, socket, named
--- pipe, char device, block device or other)
---@field mode string
--- count of hard links to the file
---@field nlink number
--- user id of owner
---@field uid number
--- group id of owner
---@field gid number
--- type of device, for files that are char/block devices
---@field rdev number|nil
--- time of last access modification (as seconds since the UNIX epoch)
---@field access number
--- time of last file status change (as seconds since the UNIX epoch)
---@field change number
--- time of the last file contents change (as seconds since the UNIX epoch)
---@field modification number
--- 9 character string specifying the user access permissions for the file. The
--- first three characters represent Read/Write/Execute permissions for the file
--- owner. The first character will be "r" if the user has read permissions, "-"
--- if they do not; the second will be "w" if they have write permissions, "-"
--- if they do not; the third will be "x" if they have execute permissions, "-"
--- if they do not. The second group of three characters follow the same
--- convention, but refer to whether or not the file's group have
--- Read/Write/Execute permissions, and the final three characters follow the
--- same convention, but apply to other system users not covered by the Owner or
--- Group fields.
---@field permissions string
--- time the file was created (as seconds since the UNIX epoch)
---@field creation number
--- file size, in bytes
---@field size number
--- number of blocks allocated for file
---@field blocks number
--- optimal file system I/O blocksize
---@field blksize number
