---@class EventTapEventProperties
--- (I) The event source Unix effective GID.
---@field eventSourceGroupID integer
--- (I) The event source state ID used to create this event.
---@field eventSourceStateID integer
--- (I) The event source Unix process ID.
---@field eventSourceUnixProcessID integer
--- (I) Event source user-supplied data, up to 64 bits.
---@field eventSourceUserData integer
--- (I) The event source Unix effective UID.
---@field eventSourceUserID integer
--- (I) The event target process serial number. The value is a 64-bit long word.
---@field eventTargetProcessSerialNumber integer
--- (I) The event target Unix process ID.
---@field eventTargetUnixProcessID integer
--- Undocumented, assumed Integer
---@field eventUnacceleratedPointerMovementX integer
--- Undocumented, assumed Integer
---@field eventUnacceleratedPointerMovementY integer
--- (I) Non-zero when this is an autorepeat of a key-down, and zero otherwise.
---@field keyboardEventAutorepeat integer
--- (I) The keyboard type identifier.
---@field keyboardEventKeyboardType integer
--- (I) The virtual keycode of the key-down or key-up event.
---@field keyboardEventKeycode integer
--- (I) The mouse button number. For information about the possible values, see Mouse Buttons.
---@field mouseEventButtonNumber integer
--- (I) The mouse button click state. A click state of 1 represents a single click. A click state of 2 represents a double-click. A click state of 3 represents a triple-click.
---@field mouseEventClickState integer
--- (I) The horizontal mouse delta since the last mouse movement event.
---@field mouseEventDeltaX integer
--- (I) The vertical mouse delta since the last mouse movement event.
---@field mouseEventDeltaY integer
--- (I) The value is non-zero if the event should be ignored by the Inkwell subsystem.
---@field mouseEventInstantMouser integer
--- (I) The mouse button event number. Matching mouse-down and mouse-up events will have the same event number.
---@field mouseEventNumber integer
--- (N) The mouse button pressure. The pressure value may range from 0 to 1, with 0 representing the mouse being up. This value is commonly set by tablet pens mimicking a mouse.
---@field mouseEventPressure number
--- (I) Encoding of the mouse event subtype. 0 = mouse, 1 = tablet point, 2 = tablet proximity, 3 = touch
---@field mouseEventSubtype integer
--- (I) Window ID of window underneath mouse pointer (this corresponds to hs.window:id())
---@field mouseEventWindowUnderMousePointer integer
--- (I) Window ID of window underneath mouse pointer that can handle this event (this corresponds to hs.window:id())
---@field mouseEventWindowUnderMousePointerThatCanHandleThisEvent integer
--- (I) Scrolling data. This field typically contains the change in vertical position since the last scrolling event from a Mighty Mouse scroller or a single-wheel mouse scroller.
---@field scrollWheelEventDeltaAxis1 integer
--- (I) Scrolling data. This field typically contains the change in horizontal position since the last scrolling event from a Mighty Mouse scroller.
---@field scrollWheelEventDeltaAxis2 integer
--- (I) This field is not used.
---@field scrollWheelEventDeltaAxis3 integer
--- (N) Contains scrolling data which represents a line-based or pixel-based change in vertical position since the last scrolling event from a Mighty Mouse scroller or a single-wheel mouse scroller.
---@field scrollWheelEventFixedPtDeltaAxis1 number
--- (N) Contains scrolling data which represents a line-based or pixel-based change in horizontal position since the last scrolling event from a Mighty Mouse scroller.
---@field scrollWheelEventFixedPtDeltaAxis2 number
--- (N) This field is not used.
---@field scrollWheelEventFixedPtDeltaAxis3 number
--- (I) Indicates whether the event should be ignored by the Inkwell subsystem. If the value is non-zero, the event should be ignored.
---@field scrollWheelEventInstantMouser integer
--- (I) Indicates whether a scrolling event contains continuous, pixel-based scrolling data. The value is non-zero when the scrolling data is pixel-based and zero when the scrolling data is line-based (note that this is the opposite of what constants in CGEventTypes.h suggest, so test before relying on and let us know what you discover!).
---@field scrollWheelEventIsContinuous integer
--- (I) Indicates scroll momentum phase: 0 = none, 1 = begin, 2 = continue, 3 = end
---@field scrollWheelEventMomentumPhase integer
--- (I) Pixel-based scrolling data. The scrolling data represents the change in vertical position since the last scrolling event from a Mighty Mouse scroller or a single-wheel mouse scroller.
---@field scrollWheelEventPointDeltaAxis1 integer
--- (I) Pixel-based scrolling data. The scrolling data represents the change in horizontal position since the last scrolling event from a Mighty Mouse scroller.
---@field scrollWheelEventPointDeltaAxis2 integer
--- (I) This field is not used.
---@field scrollWheelEventPointDeltaAxis3 integer
--- (I) The number of scroll gestures that have begun before the momentum phase of the initial gesture has ended (unverified, this is inferred from web comments).
---@field scrollWheelEventScrollCount integer
--- (I) Indicates scroll phase: 1 = began, 2 = changed, 4 = ended, 8 = cancelled, 128 = may begin.
---@field scrollWheelEventScrollPhase integer
--- (I) The system-assigned unique device ID.
---@field tabletEventDeviceID integer
--- (I) The tablet button state. Bit 0 is the first button, and a set bit represents a closed or pressed button. Up to 16 buttons are supported.
---@field tabletEventPointButtons integer
--- (N) The tablet pen pressure. A value of 0.0 represents no pressure, and 1.0 represents maximum pressure.
---@field tabletEventPointPressure number
--- (I) The absolute X coordinate in tablet space at full tablet resolution.
---@field tabletEventPointX integer
--- (I) The absolute Y coordinate in tablet space at full tablet resolution.
---@field tabletEventPointY integer
--- (I) The absolute Z coordinate in tablet space at full tablet resolution.
---@field tabletEventPointZ integer
--- (N) The tablet pen rotation.
---@field tabletEventRotation number
--- (N) The tangential pressure on the device. A value of 0.0 represents no pressure, and 1.0 represents maximum pressure.
---@field tabletEventTangentialPressure number
--- (N) The horizontal tablet pen tilt. A value of 0.0 represents no tilt, and 1.0 represents maximum tilt.
---@field tabletEventTiltX number
--- (N) The vertical tablet pen tilt. A value of 0.0 represents no tilt, and 1.0 represents maximum tilt.
---@field tabletEventTiltY number
--- (I) A vendor-specified value.
---@field tabletEventVendor1 integer
--- (I) A vendor-specified value.
---@field tabletEventVendor2 integer
--- (I) A vendor-specified value.
---@field tabletEventVendor3 integer
--- (I) The device capabilities mask.
---@field tabletProximityEventCapabilityMask integer
--- (I) The system-assigned device ID.
---@field tabletProximityEventDeviceID integer
--- (I) Indicates whether the pen is in proximity to the tablet. The value is non-zero if the pen is in proximity to the tablet and zero when leaving the tablet.
---@field tabletProximityEventEnterProximity integer
--- (I) The vendor-defined ID of the pointing device.
---@field tabletProximityEventPointerID integer
--- (I) The pointer type.
---@field tabletProximityEventPointerType integer
--- (I) The system-assigned unique tablet ID.
---@field tabletProximityEventSystemTabletID integer
--- (I) The vendor-defined tablet ID, typically the USB product ID.
---@field tabletProximityEventTabletID integer
--- (I) The vendor-defined ID, typically the USB vendor ID.
---@field tabletProximityEventVendorID integer
--- (I) The vendor-defined pointer serial number.
---@field tabletProximityEventVendorPointerSerialNumber integer
--- (I) The vendor-assigned pointer type.
---@field tabletProximityEventVendorPointerType integer
--- (I) The vendor-defined unique ID.
---@field tabletProximityEventVendorUniqueID integer
