---@class SpoonMetadata
--- Spoon's name
---@field public name string
--- Spoon's version
---@field public version string
--- Spoon's author name and email
---@field public author string
--- Spoon's license
---@field public license string
--- Spoon's homepage
---@field public homepage string|nil
--- Spoon's default hotkey mapping
---@field public defaultHotkeys table<string,HotkeyMapping>|nil
