{ config
, lib
, pkgs
, ...
}: with builtins; {
	environment.etc = {
		"nix/nix.conf" = lib.mkForce {
			enable = true;
			text = (lib.concatLines (map lib.trim (lib.splitString "\n" ''
				# WARNING: generated by nix-darwin. Do not edit it!
				accept-flake-config = true
				allowed-users = ${concatStringsSep " " config.nix.settings.allowed-users}
				auto-optimise-store = ${lib.boolToString (config.nix.settings.auto-optimise-store or false)}
				builders =
				build-users-group =
				cores = ${toString config.nix.settings.cores}
				extra-experimental-features = nix-command flakes
				extra-sandbox-paths = ${concatStringsSep " " config.nix.settings.extra-sandbox-paths}
				max-jobs = ${toString config.nix.settings.max-jobs}
				require-sigs = ${toString config.nix.settings.require-sigs}
				sandbox = ${lib.boolToString (config.nix.settings.sandbox or false)}
				sandbox-fallback = false
				ssl-cert-file = /opt/homebrew/etc/openssl@3/cert.pem
				substituters = ${concatStringsSep " " config.nix.settings.substituters} https://cache.nixos.org/
				trusted-public-keys = ${concatStringsSep " " config.nix.settings.trusted-public-keys} cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
				trusted-substituters =
				trusted-users = root ${concatStringsSep " " config.nix.settings.trusted-users}
			'')));
		};
	};

	environment.systemPackages = [
		pkgs.niv
		pkgs.nix
		pkgs.nix-init
		pkgs.nurl
	];

	nix = {
		## nix-darwin since 25.05 only supports multi-user installations; it dropped
		## all options to disable the daemon or to configure build users. This is a
		## big no-no for my work environment as I must run it as a single-user with
		## no daemon. I also prefer to run that way on my personal environment.
		##
		## Alternative: manage nix.conf directly & the nix package myself.
		## nix-store --store daemon
		enable = false;
		# useDaemon = false;
		# extraOptions = ''
		# 	accept-flake-config = true
		# 	extra-experimental-features = nix-command flakes
		# '';
		package = pkgs.nixVersions.git;
		settings = lib.mkForce {
			allowed-users = [
				"william"
			];
			auto-allocate-uids = false;
			build-users-group = "";
			extra-sandbox-paths = [
				"/opt/homebrew/etc/openssl@3/cert.pem"
			];
			sandbox = true;
			substituters = [
				"https://wwmoraes.cachix.org/"
				"https://nix-community.cachix.org/"
			];
			trusted-public-keys = [
				"wwmoraes.cachix.org-1:N38Kgu19R66Jr62aX5rS466waVzT5p/Paq1g6uFFVyM="
				"nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs="
			];
			trusted-users = [
				"@_developer"
				"@admin"
				"william"
			];
		};
	};

	## nuke the unconfigurable daemon settings since nix-darwin 25.05
	system.activationScripts.nix-daemon.text = lib.mkForce "## no-op";
}
