theme = "dark_plus"

[editor]
bufferline = "always"
cursorline = true
idle-timeout = 0
middle-click-paste = true
mouse = true
rulers = [80, 120]
shell = ["fish", "-c"]
text-width = 120
true-color = true

# [editor.auto-save]
# focus-lost = true
# after-delay.enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.gutters.line-numbers]
min-width = 3

[editor.indent-guides]
character = "┆"
render = true
skip-levels = 1

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.soft-wrap]
enable = true
wrap-at-text-width = true

[editor.statusline]
center = ["file-name", "read-only-indicator", "file-modification-indicator"]
left = ["mode", "spinner", "version-control", "workspace-diagnostics"]
mode.insert = "INSERT"
mode.normal = "NORMAL"
mode.select = "SELECT"
right = ["file-type", "diagnostics", "selections", "register", "position", "file-encoding"]
separator = "|"

[keys.insert]
S-tab = "move_parent_node_start"

[keys.normal]
";" = "command_mode"
"A-," = "goto_previous_buffer"
"A-." = "goto_next_buffer"
"A-/" = "repeat_last_motion"
"A-J" = ["extend_to_line_bounds", "yank", "paste_after"]
"A-K" = ["extend_to_line_bounds", "yank", "paste_before"]
"A-S-down" = ["extend_to_line_bounds", "yank", "paste_after"]
"A-S-up" = ["extend_to_line_bounds", "yank", "paste_before"]
"A-down" = ["extend_to_line_bounds", "delete_selection", "paste_after"]
"A-j" = ["extend_to_line_bounds", "delete_selection", "paste_after"]
"A-k" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
"A-up" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
"A-w" = ":buffer-close"
A-q = ":reflow"
C-g = [":new", ":insert-output lazygit", ":redraw", ":buffer-close"]
S-tab = "move_parent_node_start"
X = ["extend_line_up", "extend_to_line_bounds"]
p = "paste_clipboard_before"
tab = "move_parent_node_end"
y = "yank_main_selection_to_clipboard"

[keys.normal.","]
"," = "keep_primary_selection"
c = ":buffer-close"
q = ":quit"
r = [":sh chezmoi apply ~/.config/helix", ":config-reload"]
s = ":pipe sort"

[keys.select]
S-tab = "extend_parent_node_start"
X = ["extend_line_up", "extend_to_line_bounds"]
tab = "extend_parent_node_end"
