confirmOnQuit: false
quitOnTopLevelReturn: false
notARepository: skip
os:
  open: 'code -rg {{filename}}'
git:
  branchLogCmd: >-
    git log
      --color
      --graph
      --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'
      --abbrev-commit
      --date=relative {{branchName}}
      --
  allBranchesLogCmd: >-
    git log
      --color
      --graph
      --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'
      --abbrev-commit
      --date=relative
customCommands:
  - key: F
    command: git cz c
    context: files
    subprocess: true
    # loadingText:
    description: commit with commitizen
    # stream: false
    # showOutput: false
