confirmOnQuit: false
disableStartupPopups: true
notARepository: skip
quitOnTopLevelReturn: false

# services:
#   git.us.aegon.com: "github:git.us.aegon.com"

os:
  open: "code -rg {{filename}}"
  editPreset: vscode

git:

  branchLogCmd: >-
    git log
    --color
    --graph
    --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'
    --abbrev-commit
    --date=relative {{branchName}}
    --

  allBranchesLogCmd: >-
    git log
    --color
    --graph
    --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'
    --abbrev-commit
    --date=relative
    --

  commit:
    signOff: false

  overrideGpg: true

customCommands:
  - key: F
    command: koji
    context: files
    subprocess: true
    # loadingText:
    description: commit with koji
    # stream: false
    # showOutput: false
