command -q helm; or exit

complete -ec helm

complete -xc helm -s h -l help -d "help for helm"
complete -xc helm -l debug -d "Enable verbose output"
complete -rc helm -l home -d "Location of your Helm config. Overrides \$HELM_HOME (default \"$HOME/.helm\")"
complete -xc helm -l host -d "Address of Tiller. Overrides \$HELM_HOST"
complete -rc helm -l kube-context -d "Name of the kubeconfig context to use"
complete -rc helm -l kubeconfig -d "Absolute path of the kubeconfig file to be used"
complete -xc helm -l tiller-connection-timeout -d "The duration (in seconds) Helm will wait to establish a connection to Tiller (default 300)"
complete -xc helm -l tiller-namespace -d "Namespace of Tiller (default \"kube-system\")"

complete -xc helm -n '__fish_use_subcommand' -a help -d "Help about any command"
complete -xc helm -n '__fish_use_subcommand || __fish_seen_subcommand_from help' -a completion -d "Generate autocompletions script for the specified shell (bash or zsh)"
complete -xc helm -n '__fish_use_subcommand || __fish_seen_subcommand_from help' -a create -d "Create a new chart with the given name"
complete -xc helm -n '__fish_use_subcommand || __fish_seen_subcommand_from help' -a delete -d "Given a release name, delete the release from Kubernetes"
complete -xc helm -n '__fish_use_subcommand || __fish_seen_subcommand_from help' -a dependency -d "Manage a chart's dependencies"
complete -xc helm -n '__fish_use_subcommand || __fish_seen_subcommand_from help' -a diff -d "Preview helm upgrade changes as a diff"
complete -xc helm -n '__fish_use_subcommand || __fish_seen_subcommand_from help' -a fetch -d "Download a chart from a repository and (optionally) unpack it in local directory"
complete -xc helm -n '__fish_use_subcommand || __fish_seen_subcommand_from help' -a get -d "Download a named release"
complete -xc helm -n '__fish_use_subcommand || __fish_seen_subcommand_from help' -a history -d "Fetch release history"
complete -xc helm -n '__fish_use_subcommand || __fish_seen_subcommand_from help' -a home -d "Displays the location of HELM_HOME"
complete -xc helm -n '__fish_use_subcommand || __fish_seen_subcommand_from help' -a init -d "Initialize Helm on both client and server"
complete -xc helm -n '__fish_use_subcommand || __fish_seen_subcommand_from help' -a inspect -d "Inspect a chart"
complete -xc helm -n '__fish_use_subcommand || __fish_seen_subcommand_from help' -a install -d "Install a chart archive"
complete -xc helm -n '__fish_use_subcommand || __fish_seen_subcommand_from help' -a lint -d "Examines a chart for possible issues"
complete -xc helm -n '__fish_use_subcommand || __fish_seen_subcommand_from help' -a list -d "List releases"
complete -xc helm -n '__fish_use_subcommand || __fish_seen_subcommand_from help' -a package -d "Package a chart directory into a chart archive"
complete -xc helm -n '__fish_use_subcommand || __fish_seen_subcommand_from help' -a plugin -d "Add, list, or remove Helm plugins"
complete -xc helm -n '__fish_use_subcommand || __fish_seen_subcommand_from help' -a push -d "Please see https://github.com/chartmuseum/helm-push for usage"
complete -xc helm -n '__fish_use_subcommand || __fish_seen_subcommand_from help' -a repo -d "Add, list, remove, update, and index chart repositories"
complete -xc helm -n '__fish_use_subcommand || __fish_seen_subcommand_from help' -a reset -d "Uninstalls Tiller from a cluster"
complete -xc helm -n '__fish_use_subcommand || __fish_seen_subcommand_from help' -a rollback -d "Rollback a release to a previous revision"
complete -xc helm -n '__fish_use_subcommand || __fish_seen_subcommand_from help' -a search -d "Search for a keyword in charts"
complete -xc helm -n '__fish_use_subcommand || __fish_seen_subcommand_from help' -a serve -d "Start a local http web server"
complete -xc helm -n '__fish_use_subcommand || __fish_seen_subcommand_from help' -a status -d "Displays the status of the named release"
complete -xc helm -n '__fish_use_subcommand || __fish_seen_subcommand_from help' -a template -d "Locally render templates"
complete -rc helm -n '__fish_use_subcommand || __fish_seen_subcommand_from template' -s f -l values -d "Specify values in a YAML file (can specify multiple) (default [])"

complete -xc helm -n '__fish_use_subcommand || __fish_seen_subcommand_from help' -a test -d "Test a release"
complete -xc helm -n '__fish_use_subcommand || __fish_seen_subcommand_from help' -a tiller -d "Please see https://github.com/rimusz/helm-tiller for usage"
complete -xc helm -n '__fish_use_subcommand || __fish_seen_subcommand_from help' -a upgrade -d "Upgrade a release"
complete -xc helm -n '__fish_use_subcommand || __fish_seen_subcommand_from help' -a verify -d "Verify that a chart at the given path has been signed and is valid"
complete -xc helm -n '__fish_use_subcommand || __fish_seen_subcommand_from help' -a version -d "Print the client/server version information"
