[[snippets]]
description = "dig domain name"
command = "dig +nocmd <domain> <type=ANY> +multiline +noall +answer"
output = ""

[[snippets]]
description = "inspect domain certificate"
command = "openssl s_client -showcerts -servername <domain> -connect <domain>:<port=443> 2>/dev/null | openssl x509 -inform pem -noout -text"
output = ""

[[snippets]]
description = "list MAS apps in brew+nix format"
command = '''mas list | awk -F '  [ ]*' '{NF=NF-1; print "\\""$2"\\"", "=", $1";"}' | sort -u'''
output = ""
tag = ["nix", "brew"]
