---@class PathwatcherFlags
---@field mustScanSubDirs boolean
---@field userDropped boolean
---@field kernelDropped boolean
---@field eventIdsWrapped boolean
---@field historyDone boolean
---@field rootChanged boolean
---@field mount boolean
---@field unmount boolean
---@field itemCreated boolean
---@field itemRemoved boolean
---@field itemInodeMetaMod boolean
---@field itemRenamed boolean
---@field itemModified boolean
---@field itemFinderInfoMod boolean
---@field itemChangeOwner boolean
---@field itemXattrMod boolean
---@field itemIsFile boolean
---@field itemIsDir boolean
---@field itemIsSymlink boolean
--- (OS X 10.9+)
---@field ownEvent boolean
--- (OS X 10.10+)
---@field itemIsHardlink boolean
--- (OS X 10.10+)
---@field itemIsLastHardlink boolean
