[docker.config]
experimental = "disabled"
currentContext = "desktop-linux"
aliases.builder = "buildx"
features.hooks = "false"

[docker.config.auths]
"https://index.docker.io/v1/" = {}

[docker.config.plugins]
-x-cli-hints.enabled = "false"
debug.hooks = "exec"
scout.hooks = "pull,buildx build"
