{

  flake.modules.darwin.single-user =
    { config, ... }:
    with builtins;
    let
      ## https://github.com/nix-darwin/nix-darwin/blob/fa6120c32f10bd2aac9e8c9a6e71528a9d9d823b/modules/nix/default.nix#L58
      mkValueString =
        v:
        if v == null then
          ""
        else if isInt v then
          toString v
        else if isBool v then
          lib.boolToString v
        else if isFloat v then
          lib.strings.floatToString v
        else if isList v then
          toString v
        else if lib.isDerivation v then
          toString v
        else if builtins.isPath v then
          toString v
        else if isString v then
          v
        else if isCoercibleToString v then
          toString v
        else
          abort "The nix conf value: ${toPretty { } v} can not be encoded";
      mkKeyValue = k: v: "${lib.escape [ "=" ] k} = ${mkValueString v}";
      mkKeyValuePairs = attrs: concatStringsSep "\n" (lib.mapAttrsToList mkKeyValue attrs);
    in
    {
      home-manager.sharedModules = [
        (
          {
            config,
            ...
          }:
          {
            home.packages = [
              config.nix.package
            ];

            launchd.agents.nix-collect-garbage = {
              enable = true;
              config = rec {
                Label = "org.nix-community.home.nix-collect-garbage";
                ProcessType = "Background";
                ProgramArguments = [
                  (lib.getExe' config.nix.package "nix-collect-garbage")
                  "--delete-older-than"
                  "7d"
                ];
                RunAtLoad = false;
                StandardErrorPath = "${config.home.homeDirectory}/Library/Logs/${Label}.err.log";
                StandardOutPath = "${config.home.homeDirectory}/Library/Logs/${Label}.out.log";
                StartCalendarInterval = {
                  Hour = 18;
                  Minute = 0;
                  Weekday = 7;
                };
              };
            };
          }
        )
      ];

      environment.etc = {
        "nix/nix.conf" = lib.mkForce {
          enable = true;
          text = ''
            # WARNING: generated by nix-darwin. Do not edit it!
            ${mkKeyValuePairs config.nix.settings}
          '';
        };
        "nix/registry.json" = {
          # # see nixpkgs.flake.setFlakeRegistry
          text = builtins.toJSON {
            version = 2;
            flakes = lib.mapAttrsToList (n: v: { inherit (v) from to exact; }) config.nix.registry;
          };
        };
      };

      environment.systemPackages = [
        config.flake.packages.${pkgs.stdenv.hostPlatform.system}.darwin-rebuild
        config.flake.packages.${pkgs.stdenv.hostPlatform.system}.switch-system
        config.nix.package
      ];

      environment.variables = {
        # see nixpkgs.flake.setFlakeRegistry
        NIX_PATH = [
          "nixpkgs=flake:nixpkgs"
          # "${config.system.primaryUserHome}/.nix-defexpr/channels"
          "/nix/var/nix/profiles/per-user/root/channels"
        ];
      };

      nix = {
        ## nix-darwin since 25.05 only supports multi-user installations; it dropped
        ## all options to disable the daemon or to configure build users. This is a
        ## big no-no for my work environment as I must run it as a single-user with
        ## no daemon.
        ##
        ## Alternative: manage nix.conf directly & the nix package myself.
        enable = false;
        settings = {
          build-users-group = lib.mkDefault "";
          substituters = lib.mkAfter [
            [
              "https://cache.nixos.org/"
            ]
          ];
          trusted-public-keys = lib.mkAfter [
            [
              "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY="
            ]
          ];
        };
        registry = {
          nixpkgs.to = lib.mkDefault {
            # see nixpkgs.flake.setFlakeRegistry
            type = "path";
            path = config.nixpkgs.flake.source;
          };
        };
      };

      ## single-user mode requires nix.enable = false, which is incompatible with
      ## this; thus we set it ourselves :D
      # nixpkgs.flake.setFlakeRegistry = true;

      system.checks.verifyBuildUsers = false;

      ## nuke the unconfigurable daemon settings since nix-darwin 25.05
      system.activationScripts.nix-daemon.text = lib.mkForce ":";

      system.tools.darwin-rebuild.enable = false;
    };
}
